services:
  airflow:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./dbt_project:/opt/airflow/dbt_project
      - ./data_generator:/opt/airflow/data_generator
      - airflow_data:/opt/airflow
    command: standalone

volumes:
  airflow_data:
