version: 2

models:
  - name: stg_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - unique
          - not_null

  - name: stg_subscriptions
    columns:
      - name: subscription_id
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_users')
                field: user_id
      - name: plan
        tests:
          - accepted_values:
              arguments:
                values: ['free', 'pro', 'enterprise']
      - name: status
        tests:
          - accepted_values:
              arguments:
                values: ['active', 'canceled']

  - name: stg_events
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_users')
                field: user_id

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: subscription_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_subscriptions')
                field: subscription_id
      - name: status
        tests:
          - accepted_values:
              arguments:
                values: ['success', 'failed']
