version: 2

models:
  - name: dim_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null

  - name: fct_churn
    columns:
      - name: churn_type
        tests:
          - accepted_values:
              arguments:
                values: ['voluntary', 'involuntary']
